name: Manual Workflow with Checkboxes
on:
  workflow_dispatch:
    inputs:
      checkbox_1:
        description: 'Terraform Nodes'
        required: false
        default: false
      checkbox_2:
        description: 'KOPS Installation'
        required: false
        default: false
      checkbox_3:
        description: 'EFK Installation'
        required: false
        default: false
      checkbox_4:
        description: 'Monitoring Installation'
        required: false
        default: false

jobs:
  run_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check selected checkboxes and run commands
        run: |
          if [[ "${{ github.event.inputs.checkbox_1 }}" == true ]]; then
            echo "Creating Nodes"
            # Replace this echo command with your actual command for Checkbox 1
          fi

          if [[ "${{ github.event.inputs.checkbox_2 }}" == true ]]; then
            echo "Installing KOPS"
            # Replace this echo command with your actual command for Checkbox 2
          fi

          if [[ "${{ github.event.inputs.checkbox_3 }}" == true ]]; then
            echo "Setting up EFK"
            # Replace this echo command with your actual command for Checkbox 3
          fi

          if [[ "${{ github.event.inputs.checkbox_4 }}" == true ]]; then
            echo "Setting up Grafana"
            # Replace this echo command with your actual command for Checkbox 4
          fi
