name: Manual Workflow with Checkboxes
on:
  workflow_dispatch:
    inputs:
      checkbox_1:
        description: 'Terraform Nodes'
        required: false
        default: false
      checkbox_2:
        description: 'KOPS Installation'
        required: false
        default: false
      checkbox_3:
        description: 'EFK Installation'
        required: false
        default: false
      checkbox_4:
        description: 'Monitoring Installation'
        required: false
        default: false

jobs:
  run_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Display selected checkboxes
        run: |
          echo "Checkbox 1: ${{ github.event.inputs.checkbox_1 }}"
          echo "Checkbox 2: ${{ github.event.inputs.checkbox_2 }}"
          echo "Checkbox 3: ${{ github.event.inputs.checkbox_3 }}"
          echo "Checkbox 4: ${{ github.event.inputs.checkbox_4 }}"
